version: '3'

services:
  airflow:
    image: docker-whirl-airflow:local
    ports:
      - '5000:5000'  # HTTP (Airflow Web UI)
    volumes:
      - ${DAG_FOLDER}:/usr/local/airflow/dags/$PROJECTNAME
      - ${ENVIRONMENT_FOLDER}/whirl.setup.d:/etc/airflow/whirl.setup.d/env.d/
      - ${DAG_FOLDER}/whirl.setup.d:/etc/airflow/whirl.setup.d/dag.d/
