version: '3'

services:
  airflow:
    image: docker-whirl-airflow:local
    ports:
      - '5000:5000'  # HTTP (Airflow Web UI)
    volumes:
      - ${DAG_FOLDER}:/usr/local/airflow/dags/$PROJECTNAME
      - ${ENVIRONMENT_FOLDER}/preparations:/etc/airflow/preparations.d/env.d/
      # - ${DAG_FOLDER}/preparations:/etc/airflow/preparations.d/dag.d/
