version: '3'

services:
  airflow:
    image: docker-whirl-airflow:py-${PYTHON_VERSION}-local
    command: ["singlemachine"]
    ports:
      - '5000:5000'  # HTTP (Airflow Web UI)
    env_file:
      - .whirl.env
    environment:
      - WHIRL_SETUP_FOLDER
      - UNPAUSE_DAG
    volumes:
      - ${DAG_FOLDER}:/opt/airflow/dags/$PROJECTNAME
      - ${ENVIRONMENT_FOLDER}/whirl.setup.d:${WHIRL_SETUP_FOLDER}/env.d/
      - ${DAG_FOLDER}/whirl.setup.d:${WHIRL_SETUP_FOLDER}/dag.d/
      - ${MOCK_DATA_FOLDER}:/mock-data
    depends_on:
      - s3server
    links:
      - s3server:${DBT_BUCKET}.s3server

  s3server:
    build:
      context: ${DOCKER_CONTEXT_FOLDER}/patched-localstack
      dockerfile: Dockerfile
    ports:
      - "4563-4584:4563-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DBT_BUCKET
      - AWS_SERVER
      - AWS_PORT
      - PORT_WEB_UI
