version: '3'

services:
  mysql:
    image: mysql:5.7
    env_file:
      - mysql.env
  ftp-server:
    image: atmoz/sftp
    ports:
        - 22:22
    env_file:
      - sftp.env
  airflow:
    image: docker-whirl-airflow:local
    ports:
      - '5000:5000'  # HTTP (Airflow Web UI)
    env_file:
      - mysql.env
      - sftp.env
    environment:
      - DAG_FOLDER
      - PROJECT_NAME
      - MOCK_DATA_FOLDER
    volumes:
      - $DAG_FOLDER:/usr/local/airflow/dags/$PROJECTNAME
      - $MOCK_DATA_FOLDER:/mock-data
      - ./preparations:/etc/airflow/preparations.d/env.d
    depends_on:
      - ftp-server
      - mysql
