name: execute whirl ci for examples
on:
  push:
    branches:
  pull_request:
    branches:
      - master
jobs:
  whirl-ci-api-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run whirl CI
        working-directory: ./examples/api-to-s3
        run: ../../whirl ci
