name: execute whirl ci for examples
on:
  push:
    branches:
  pull_request:
    branches:
      - master
jobs:
  whirl-ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        example: ['./examples/api-to-s3', './examples/localhost-ssh-example']
    steps:
      - uses: actions/checkout@v2
      - name: Run whirl CI
        working-directory: ${{ matrix.example }}
        run: |
          echo Run Ci for example ${{ matrix.example }}
          ../../whirl ci
